$(document).ready(function(){
  $(".create-icon").hover(function(){
    $(".create").fadeToggle(100)
  })
  $(".notification-icon").hover(function(){
    $(".create1").fadeToggle(100)
  })
  $(".search1").hover(function(){
    $(".create2").fadeToggle(100)
  })
  $(".mike1").hover(function(){
    $(".create3").fadeToggle(100)
  })
  $(".search-icon").hover(function(){
    $(".create4").fadeToggle(100)
  })
  $(".mike-icon").hover(function(){
    $(".create5").fadeToggle(100)
  })
  $(".threelines").click(function(){
    $(".aside-a").show(100)
  })
  $(".threelines1").click(function(){
    $(".aside-a").hide(100)
  })
  $(".left-sidebar-button").click(function(){
    $(".t").css({"display":"flex"})
    $(".t").show()
    $(".k").hide()
    $(".l").css({"display":"flex"})
    $(".l").show()
  })
  $(".left-sidebar-button1").click(function(){
    $(".t").hide()
    $(".l").hide()
    $(".k").show()
  })
  $(".more1").click(function(){
    $(".more1").hide()
    $(".para7").show()
    $(".less1").show()
    $(".spant1").hide()
    $(".spant2").show()
  })
  $(".less1").click(function(){
    $(".less1").hide()
    $(".para7").hide()
    $(".more1").show()
    $(".spant2").hide()
    $(".spant1").show()
  })
  $(".button1121a").click(function(){
    $(this).css({"background-color":"rgb(217, 217, 217)"})
    $(".button1121b").css({"background-color":"white"})
    $(".topcomment").show()
    $(".newcomment").hide()
  })
  $(".button1121b").click(function(){
    $(this).css({"background-color":"rgb(217, 217, 217)"})
    $(".button1121a").css({"background-color":"white"})
    $(".topcomment").hide()
    $(".newcomment").show()
  })
  $(".comment1120").click(function(){
    $(".comment1121").toggle()
  })
  $(".input312").click(function(){
    $(".comment313").show()
    $(".comment313").css({"display":"flex"})
  })
  $(".button3132a").click(function(){
    $(".comment313").hide()
  })
  $(".buy").click(function(){
    $(".buy").hide()
    $(".bui").show()
    $(".opo").show()
    $(".opo").css({"display":"flex"})
  })
  $(".bui").click(function(){
    $(".bui").hide()
    $(".buy").show()
    $(".opo").hide()
  })
})